import json
from pathlib import Path

import numpy as np
from sentence_transformers import SentenceTransformer


FACTS_PATH = Path("memory/extracted_facts/auto_facts.json")
MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"

TOP_K_DEFAULT = 8


_model = None
_facts = None
_fact_texts = None
_fact_embeds = None


def get_model():
    global _model
    if _model is None:
        _model = SentenceTransformer(MODEL_NAME)
    return _model


def load_facts():
    global _facts, _fact_texts, _fact_embeds

    if _facts is not None:
        return _facts, _fact_texts, _fact_embeds

    if not FACTS_PATH.exists():
        _facts = []
        _fact_texts = []
        _fact_embeds = np.zeros((0, 384), dtype=np.float32)
        return _facts, _fact_texts, _fact_embeds

    with open(FACTS_PATH, "r", encoding="utf-8") as f:
        _facts = json.load(f)

    _fact_texts = [fact_to_retrieval_text(fact) for fact in _facts]

    model = get_model()
    _fact_embeds = model.encode(
        _fact_texts,
        normalize_embeddings=True,
        show_progress_bar=False,
    )

    return _facts, _fact_texts, _fact_embeds


def fact_to_retrieval_text(fact):
    """
    Prefer the rich retrieval_text generated by v4.1 extract_facts.py.
    Fall back to summary for older facts.
    """
    if fact.get("retrieval_text"):
        return fact["retrieval_text"]

    pieces = [
        fact.get("summary", ""),
        "file: " + fact.get("file", ""),
        "symbol: " + str(fact.get("symbol") or ""),
        "signature: " + str(fact.get("signature") or ""),
        "tags: " + ", ".join(fact.get("tags", [])),
        "responsibilities: " + "; ".join(fact.get("responsibilities", [])),
        "questions: " + "; ".join(fact.get("answers_questions", [])),
        "source: " + fact.get("source_excerpt", "")[:1200],
    ]
    return "\n".join(p for p in pieces if p.strip())


def format_fact_for_prompt(fact):
    """
    Keep prompt context compact but grounded.
    """
    file = fact.get("file", "")
    symbol = fact.get("symbol")
    line_start = fact.get("line_start")
    line_end = fact.get("line_end")

    location = file
    if line_start and line_end:
        location += f":{line_start}-{line_end}"

    header = f"[{fact.get('type', 'fact')}] {location}"
    if symbol:
        header += f" :: {symbol}"

    parts = [
        header,
        "Summary: " + fact.get("summary", ""),
    ]

    if fact.get("signature"):
        parts.append("Signature: " + fact["signature"])

    if fact.get("responsibilities"):
        parts.append("Responsibilities: " + "; ".join(fact["responsibilities"][:4]))

    if fact.get("tags"):
        parts.append("Tags: " + ", ".join(fact["tags"]))

    excerpt = fact.get("source_excerpt", "")
    if excerpt:
        parts.append("Source excerpt:\n" + excerpt[:1200])

    return "\n".join(parts)


def load_memory(task, top_k=TOP_K_DEFAULT):
    facts, fact_texts, fact_embeds = load_facts()

    if not facts:
        return ""

    model = get_model()
    query_embed = model.encode(
        [task],
        normalize_embeddings=True,
        show_progress_bar=False,
    )[0]

    scores = fact_embeds @ query_embed
    top_indices = np.argsort(scores)[::-1][:top_k]

    selected = []
    for idx in top_indices:
        fact = facts[int(idx)]
        selected.append(format_fact_for_prompt(fact))

    return "\n\n---\n\n".join(selected)